name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
        run: pip install -r requirements-dev.txt
      - name: Lint Ruff
        run: ruff check .

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
        run: pip install -r requirements-dev.txt
      - name: Check types
        run: mypy .